### ISSUE TITLE
Make LIDAR communication fault resistant

### ISSUE THREAD

**Issue by bmegli** [bmegli/ev3dev-mapping#22]
This needs:
- [x] configurable crc failure resistance in [xv11lidar](https://github.com/bmegli/xv11lidar/) library
- [x] config and use of above  in `ev3laser` in  [ev3dev-mapping-modules](https://github.com/bmegli/ev3dev-mapping-modules/)
- [x] config and module call in `Laser` in [ev3dev-mapping-ui](https://github.com/bmegli/ev3dev-mapping-ui/)

**Comment by bmegli** [comment]
Implemented in 'lidar-fault-tolerance' branches and waiting for test with hardware

**Comment by bmegli** [comment]
CRC failure tolerance is still not enough.

The LIDAR sometimes gets out of sync for some reason and resync is necessary.

This happens a lot with one of my units and almost never with the second.

**Comment by bmegli** [comment]
reopen bmegli/ev3dev-mapping-ui#38

**Comment by grobarko** [comment]
@bmegli I'm working also on a project, trying to do SLAM with EV3 + XV11Lidar + CruizCore + XG1300L. I'm also experiencing some issues with the LIDAR, one of which is sync being lost.
- I think the problem with the sync being lost might actually be a performance problem. If I try to cut on other functionality and precious CPU time, the sync lost problem is gone. (Also, if you rotate faster ~290RPM, vs slower ~250RPM, the frequency of the sync problem is higher, which supports my "hypothesis") Do you find this plausible? 
- Both of my units NEVER send all 90 frames for one rotation, they both skip 0-5 frames (sometimes also the first one 0xA0). Based on your implementation, I think you also expect skipping frames to happen. In this case, I find it difficult to gather 
- One of my units (I think this might be because of some damage done to it, or hardware malfunction), when scanning and when comes to angle 0xAA, the next three frames it sends are from totally "random" (by the look of it) angles (sometimes 0xF9, 0xBB, 0xC4, sometimes three completely different angles, out of order), and then it continues with the rest of the frame. Also, when it comes to those frames, the RPM value that it sends get's 50% smaller, although, visually, the rotation of the LIDAR remains with ~constant speed all the time. Have you experienced something similar, or would you have any ideas for a possible underlying cause?

**Comment by bmegli** [comment]
Hi @grobarko,

> One of my units (I think this might be because of some damage done to it, or hardware malfunction), when scanning and when comes to angle 0xAA, the next three frames it sends are from totally "random" (by the look of it) angles (sometimes 0xF9, 0xBB, 0xC4, sometimes three completely different angles, out of order), and then it continues with the rest of the frame. Also, when it comes to those frames, the RPM value that it sends drops by 50%, although, visually, the rotation of the LIDAR remains with ~constant speed all the time. Have you experienced something similar, or would you have any ideas for a possible underlying cause?

I have seen RPM drops when rotating LIDAR the wrong way (should be CCW, problem happens when rotating CW). There is optical encoder inside the lidar and some plates. One plate has different length. If you approach it rotating wrong way it takes more time and it confuses speed detection algorithm (reports lower speed) and may confuse position detection. Make sure you are rotating CCW, counterclockwise.

The fact that it happens at fixed angle also supports cause by optical encoder detecting the plate with different length at unexpected time.

> Both of my units NEVER send all 90 frames for one rotation, they both skip 0-5 frames (sometimes also the first one 0xA0). Based on your implementation, I think you also expect skipping frames to happen.

From what I observed it only happens at the beginning, when lidar starts rotating. After some time it starts to work stable. I believe I am not experiencing skipped frames at this stage, only CRC failures.

Specifically, I don't really remember hitting this [line](https://github.com/bmegli/xv11lidar/blob/master/xv11lidar.c#L309)

Also make sure you are rotating CCW first, it might be some side effect of speed/position detection problem. 

> I think the problem with the sync being lost might actually be a performance problem. If I try to cut on other functionality and precious CPU time, the sync lost problem is gone. (Also, if you rotate faster ~290RPM, vs slower ~250RPM, the frequency of the sync problem is higher, which supports my "hypothesis") Do you find this plausible?

In theory it shouldn't, the UARTs have hardware buffers (I don't remember how big), and the kernel worker should be moving data to its internal buffers, so no data should be gone. If it is you should see something in the logs (`dmesg`, things like too much work for IRQ XX). So much for the theory, I have seen strange things happen under extreme load. I am not sure if what is happening in ev3dev is equivalent to what is happening in leJOS on low level.

As far as my empirical tests show:
- it's worse at the beginning (cold laser)
- it's worse if battery is fully charged and EV3 plugged to charger (if you are interfacing LIDARs directly to EV3), gets better when battery is not full.

Kind regards,

**Comment by bmegli** [comment]
This is how the plates detected by the optical encoder look:
(this might be the reason for your symptoms if spinning CW instead of CCW)

![lidar_plates](https://user-images.githubusercontent.com/9095769/37210661-d4b25f8a-23a9-11e8-998d-e91508c1f8b3.jpg)

**Comment by grobarko** [comment]
Hey @bmegli. You were absolutely right. I was indeed spinning the LIDAR cw. I was previously using `ev3dev` and had set this up properly, but after migrating to `leJOS` (primarily, for the `Differential Pilot implementation`) this absolutely slipped my mind.

This solved the `skipped frames problems`. It also solved the `RPM drop problem`.

Also, now I'm easily able to "sync" the readings.

>  I have seen strange things happen under extreme load. I am not sure if what is happening in ev3dev is equivalent to what is happening in leJOS on low level.

I have maybe experienced something in the same line. When the robot receives movements command and starts up the motors, i.e. the load increases, the "sync" get's lost and reestablished sometimes.

Regards

**Comment by bmegli** [comment]
Ok @grobarko,

I am happy that it fixed your problem. I experienced same problems in the past, spinning the wrong way, plotting spreed on circular chart and dissasembling the lidar.

The photo is from Wayne’s tinkering page, also nice writeup on x11.

Anyway, the library waits for rewrite so that it can resync automatically.

In ev3dev not setting other-uart mode will also lead to occasional errors (sensor detection drives the pins).

Kind regards
